artist/urls.py
from django.urls import path

from artist.views import artist_list, select_artist, artist_sns, subscribe_list

app_name = "artist"

urlpatterns = [
    path('<str:category>/', artist_list, name='artist_list'), # 아티스트 조회
    path('<str:category>/subscribe/', subscribe_list, name='subscribe_list'), # 구독한 아티스트 조회
    path('<int:pk>/select/', select_artist, name='select_artist'),  # 아티스트 선택 후 아티스트 정보 페이지 이동
    path('<int:pk>/sns/', artist_sns, name='artist_sns'), # sns 페이지 이동
]

post/urls.py
from django.urls import path, include

from post.views import post_list, create_post, edit_post, delete_post, post_detail, create_comment, delete_comment

app_name = 'post'

urlpatterns = [
    path('<int:artist_pk>/<str:category>/', post_list, name='post_list'),
    path('create/<int:artist_pk>/', create_post, name='create_post'),
    path('detail/<int:pk>/', post_detail, name='post_detail'),
    path('edit/<int:pk>/', edit_post, name='edit_post'),
    path('deletePost/<int:pk>/', delete_post, name='delete_post'),
    path('createComment/<int:pk>/', create_comment, name='create_comment'),
    path('deleteComment/<int:pk>/', delete_comment, name='delete_comment'),

]

project/artist/urls.py
from django.urls import path

from artist.views import artist_list, select_artist, artist_sns, subscribe_list

app_name = "artist"

urlpatterns = [
    path('<str:category>/', artist_list, name='artist_list'), # 아티스트 조회
    path('<str:category>/subscribe/', subscribe_list, name='subscribe_list'), # 구독한 아티스트 조회
    path('<int:pk>/select/', select_artist, name='select_artist'),  # 아티스트 선택 후 아티스트 정보 페이지 이동
    path('<int:pk>/sns/', artist_sns, name='artist_sns'), # sns 페이지 이동

]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls'), name="main"),
    path('meeting/', include('meeting.urls')),
    path('artist/', include('artist.urls')),
    path('userWorking/', include('userWorking.urls')),
    path('post/', include('post.urls')),
    path('alert/', include('alert.urls')),
    path('support/', include('support.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

artist/models.py
from enum import Enum

from django.db import models

class Category(Enum):
    KPOP = 'KPOP'
    트로트 = '트로트'
    발라드 = '발라드'
    기타 = '기타'


class Artist(models.Model):
    category = models.CharField(max_length=10, choices=[(status.value, status.name) for status in Category])
    artistName = models.CharField(max_length=50)
    members = models.CharField(max_length=200, null=True)
    artistImage = models.ImageField()

    instagram = models.URLField()
    twitter = models.URLField()
    youtube = models.URLField()

    debutDate = models.DateField()
    color = models.CharField(max_length=30)
    fanName = models.CharField(max_length=30)
    agency = models.CharField(max_length=30)

    def __str__(self):
        return self.artistName

project/artist/models.py
from enum import Enum

from django.db import models

class Category(Enum):
    KPOP = 'KPOP'
    트로트 = '트로트'
    발라드 = '발라드'
    기타 = '기타'


class Artist(models.Model):
    category = models.CharField(max_length=10, choices=[(status.value, status.name) for status in Category], default=Category.기타.value)
    artistName = models.CharField(max_length=50, null=False)
    members = models.CharField(max_length=200, null=True)
    artistImage = models.ImageField(null=False)

    instagram = models.URLField()
    twitter = models.URLField()
    youtube = models.URLField()

    debutDate = models.DateField()
    color = models.CharField(max_length=30)
    fanName = models.CharField(max_length=30)
    agency = models.CharField(max_length=30)



    def __str__(self):
        return self.artistName

artist/views.py
from django.utils import timezone
from django.shortcuts import render, get_object_or_404, redirect

from alert.models import Alert
from artist.models import Artist
from userWorking.models import UserWorking


# 아티스트 조회
def artist_list(request, category):
    user = request.user

    if user.is_authenticated:
        if request.method == 'GET': # 로그인 시 get 요청
            artists = Artist.objects.all()

        if request.method == 'POST': # 다른 아티스트 보러가기 시 post 요청
            if category == 'none':
                artists = Artist.objects.all()
            else: # 필터링
                artists = Artist.objects.filter(category=category)

        return render(request, 'artist/artist_list.html', context={'artists': artists})

    return redirect('user:login')

# 구독한 아티스트 조회
def subscribe_list(request, category):
    user = request.user

    if user.is_authenticated:
        if request.method == 'GET': # 로그인 시 get 요청
            artists = user.artists.all()

        if request.method == 'POST': # 필터링 시 post 요청
            artists = user.artists.all().filter(category=category)

        return render(request, 'artist/subscribe_list.html', context={'artists': artists})

    return redirect('user:login')



# 아티스트 선택 후 아티스트 정보 페이지 이동, 해당 아티스트 userWorking 생성
def select_artist(request, pk):
    if request.user.is_authenticated:
        user = request.user
        artist = get_object_or_404(Artist, pk=pk)
        alerts = Alert.objects.filter(user=user)

        # 유저 아티스트 필드에 추가
        user.artists.add(artist)

        # userWorking 생성

        if not UserWorking.objects.filter(user=user, artist=artist).exists():
            UserWorking.objects.create(
                user=user,
                artist=artist,
                startDay=timezone.now().date()
            )

        return render(request, 'artist/artist_info.html', context={'artist':artist, 'alerts':alerts})

    return redirect('user:login')

# sns 페이지 이동
def artist_sns(request, pk):
    user=request.user
    artist = get_object_or_404(Artist, pk=pk)
    alerts = Alert.objects.filter(user=user)

    if request.method == 'POST':
        return render(request, 'artist/artist_sns.html', context={'artist':artist, 'alerts':alerts})

project/artist/views.py
from django.utils import timezone
from django.shortcuts import render, get_object_or_404, redirect

from alert.models import Alert
from artist.models import Artist
from userWorking.models import UserWorking



# 아티스트 조회
def artist_list(request, category):
    user = request.user

    if user.is_authenticated:
        if request.method == 'GET': # 로그인 시 get 요청
            artists = Artist.objects.filter(category='트로트')

        if request.method == 'POST': # 다른 아티스트 보러가기 시 post 요청
            if category == 'none':
                artists = Artist.objects.all()
            else: # 필터링

                artists = Artist.objects.filter(category=category)

        return render(request, 'artist/artist_list.html', context={'artists': artists, 'selected_category':category})

    return redirect('user:login')

# 구독한 아티스트 조회0
def subscribe_list(request, category):
    user = request.user

    if user.is_authenticated:
        if request.method == 'GET': # 로그인 시 get 요청
            artists = user.artists.all()

        if request.method == 'POST': # 필터링 시 post 요청
            artists = user.artists.all().filter(category=category)

        return render(request, 'artist/subscribe_list.html', context={'artists': artists, 'selected_category':category})

    return redirect('user:login')



# 아티스트 선택 후 아티스트 정보 페이지 이동, 해당 아티스트 userWorking 생성
def select_artist(request, pk):
    if request.user.is_authenticated:
        user = request.user
        artist = get_object_or_404(Artist, pk=pk)
        alerts = Alert.objects.filter(user=user)

        # 유저 아티스트 필드에 추가
        user.artists.add(artist)

        # userWorking 생성

        if not UserWorking.objects.filter(user=user, artist=artist).exists():
            UserWorking.objects.create(
                user=user,
                artist=artist,
                startDay=timezone.now().date()
            )

        return render(request, 'artist/artist_info.html', context={'artist':artist, 'alerts':alerts})

    return redirect('user:login')

# sns 페이지 이동
def artist_sns(request, pk):
    user=request.user
    artist = get_object_or_404(Artist, pk=pk)
    alerts = Alert.objects.filter(user=user)

    if request.method == 'POST':
        return render(request, 'artist/artist_sns.html', context={'artist':artist, 'alerts':alerts})

artist/templates/artist/artist_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>아티스트 상세 정보</title>
</head>
<body>
    {% include 'header.html' with artist=artist alerts=alerts%}
    <form method="post" action="{% url 'artist:select_artist' pk=artist.pk %}">
        {% csrf_token %}
        <button type="submit">아티스트 정보</button>
    </form>

    <form method="post" action="{% url 'artist:artist_sns' pk=artist.pk %}">
        {% csrf_token %}
        <button type="submit">SNS 보기</button>
    </form>

    </form>
    <div>{{ artist.artistName }}</div>
    <div>{{ artist.members }}</div>
    <div><img src="{{ artist.artistImage.url }}"></div>
    <div>{{ artist.instagram }}</div>
    <div>{{ artist.twitter }}</div>
    <div>{{ artist.youtube }}</div>
    <div>{{ artist.debutDate }}</div>
    <div>{{ artist.color }}</div>
    <div>{{ artist.fanName }}</div>
    <div>{{ artist.agency }}</div>

    {% include 'footer.html' with artist=artist %}

</body>
</html>

artist/templates/artist/artist_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>아티스트 선택</title>
</head>
<body>
    <form method="post" action="{% url 'artist:artist_list' category='KPOP' %}">
        {% csrf_token %}
        <button type="submit">K-POP</button>
    </form>

    <form method="post" action="{% url 'artist:artist_list' category='트로트' %}">
        {% csrf_token %}
        <button type="submit">트로트</button>
    </form>

    <form method="post" action="{% url 'artist:artist_list' category='발라드' %}">
        {% csrf_token %}
        <button type="submit">발라드</button>
    </form>

    <form method="post" action="{% url 'artist:artist_list' category='기타' %}">
        {% csrf_token %}
        <button type="submit">기타</button>
    </form>

    {% for artist in artists %}
    <form method="post" action="{% url 'artist:select_artist' pk=artist.pk %}">
        {% csrf_token %}
        <button type="submit">
             <img src="{{ artist.artistImage.url }}" width="150" height="100">
             {{ artist.artistName }}
        </button>
    </form>
    {% endfor %}
</body>
</html>

artist/templates/artist/artist_sns.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SNS</title>
</head>
<body>
    {% include 'header.html' with artist=artist alerts=alerts%}
    <form method="post" action="{% url 'artist:select_artist' pk=artist.pk %}">
        {% csrf_token %}
        <button type="submit">아티스트 정보</button>
    </form>

    <form method="post" action="{% url 'artist:artist_sns' pk=artist.pk %}">
        {% csrf_token %}
        <button type="submit">SNS 보기</button>
    </form>

    {{ artist.artistName }}

    {% include 'footer.html' with artist=artist %}
</body>
</html>

artist/templates/artist/subscribe_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>구독한 아티스트</title>
</head>
<body>

    <form method="get" action="{% url 'artist:subscribe_list' category='KPOP' %}">
        {% csrf_token %}
        <button type="submit">K-POP</button>
    </form>

    <form method="post" action="{% url 'artist:subscribe_list' category='트로트' %}">
        {% csrf_token %}
        <button type="submit">트로트</button>
    </form>

    <form method="post" action="{% url 'artist:subscribe_list' category='발라드' %}">
        {% csrf_token %}
        <button type="submit">발라드</button>
    </form>

    <form method="post" action="{% url 'artist:subscribe_list' category='기타' %}">
        {% csrf_token %}
        <button type="submit">기타</button>
    </form>

    {% for artist in artists %}
    <form method="post" action="{% url 'artist:select_artist' pk=artist.pk %}">
        {% csrf_token %}
        <button type="submit">
             <img src="{{ artist.artistImage.url }}" width="150" height="100">
             {{ artist.artistName }}
        </button>
    </form>
    {% endfor %}
    <form method="post" action="{% url 'artist:artist_list' category='none' %}">
         {% csrf_token %}
         <button type="submit">다른 아티스트 찾으러 가기 ></button>
    </form>
</body>
</html>