post/urls.py
from django.urls import path, include

from post.views import post_list, create_post, edit_post, delete_post, post_detail, create_comment, delete_comment

app_name = 'post'

urlpatterns = [
    path('<int:artist_pk>/<str:category>/', post_list, name='post_list'),
    path('create/<int:artist_pk>/', create_post, name='create_post'),
    path('detail/<int:pk>/', post_detail, name='post_detail'),
    path('edit/<int:pk>/', edit_post, name='edit_post'),
    path('deletePost/<int:pk>/', delete_post, name='delete_post'),
    path('createComment/<int:pk>/', create_comment, name='create_comment'),
    path('deleteComment/<int:pk>/', delete_comment, name='delete_comment'),

]

project/post/urls.py
from django.urls import path, include

from post.views import post_list, create_post, edit_post, delete_post, post_detail, create_comment, delete_comment

app_name = 'post'

urlpatterns = [
    path('<int:artist_pk>/<str:category>/', post_list, name='post_list'),
    path('create/<int:artist_pk>/', create_post, name='create_post'),
    path('detail/<int:pk>/', post_detail, name='post_detail'),
    path('edit/<int:pk>/', edit_post, name='edit_post'),
    path('deletePost/<int:pk>/', delete_post, name='delete_post'),
    path('createComment/<int:pk>/', create_comment, name='create_comment'),
    path('deleteComment/<int:pk>/', delete_comment, name='delete_comment'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls'), name="main"),
    path('meeting/', include('meeting.urls')),
    path('artist/', include('artist.urls')),
    path('userWorking/', include('userWorking.urls')),
    path('post/', include('post.urls')),
    path('alert/', include('alert.urls')),
    path('support/', include('support.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

support/urls.py
from django.urls import path
from support.views import support_list, create_support, support_list_complete, support_dtl, create_support_form, \
    my_support_list, my_support_list_complete

app_name = "support"

urlpatterns = [
    # 전체목록
    path('<int:pk>/posts/', support_list, name='support_list'),
    path('<int:pk>/posts/complete/', support_list_complete, name='support_list_complete'),
    path('<int:pk>/my/', my_support_list, name='my_support_list'),
    path('<int:pk>/my/complete/', my_support_list_complete, name='my_support_list_complete'),
    # 생성
    path('<int:pk>/new/', create_support, name='create_support'),
    # 상세보기
    path('<int:pk>/post/<int:spt_pk>/', support_dtl, name='support_dtl'),
    # 수정
    # 삭제
    # 모금정보 작성
    path('<int:pk>/post/<int:spt_pk>/form/', create_support_form, name='create_support_form')
]

post/models.py
from enum import Enum
from django.utils import timezone

from django.db import models

from artist.models import Artist

from user.models import User


class Category(Enum):
    가수 = '가수'
    자유 = '자유'

class Post(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.CharField(max_length=10, choices=[(status.value, status.name) for status in Category], default=Category.가수.value)

    image = models.ImageField(null=True)
    title = models.CharField(max_length=50)
    contents = models.TextField(max_length=1000)
    regTime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    contents = models.TextField(max_length=200)
    regTime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.post.title

project/post/models.py
from enum import Enum
from django.utils import timezone

from django.db import models

from artist.models import Artist

from user.models import User


class Category(Enum):
    가수 = '가수'
    자유 = '자유'

class Post(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.CharField(max_length=10, choices=[(status.value, status.name) for status in Category], default=Category.가수.value)

    image = models.ImageField(null=True)
    title = models.CharField(max_length=50, null=False)
    contents = models.TextField(max_length=1000, null=False)
    regTime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    contents = models.TextField(max_length=200, null=False)
    regTime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.post.title

post/views.py
from alert.models import Alert
from django.shortcuts import render, redirect, get_object_or_404

from artist.models import Artist
from post.models import Post, Comment
from userWorking.models import UserWorking


# 게시글 전체 조회, 카테고리 분류
def post_list(request, artist_pk, category):
    user = request.user
    alerts = Alert.objects.filter(user=user)

    if not user.is_authenticated:
        return redirect('user:login')


    artist = Artist.objects.get(pk=artist_pk)
    posts = Post.objects.filter(category=category, artist=artist)

    return render(request, 'post/post_list.html', context={'posts':posts, 'artist':artist, 'alerts':alerts})

# 게시글 상세 조회
def post_detail(request, pk):
    user = request.user
    alerts = Alert.objects.filter(user=user)

    if not user.is_authenticated:
        return redirect('user:login')

    if request.method == 'GET':
        post = Post.objects.get(pk=pk)
        comments = Comment.objects.filter(post=post)

        return render(request, 'post/post_detail.html', context={'post':post, 'comments':comments, 'artist':post.artist, 'alerts':alerts})

# 게시글 생성
def create_post(request, artist_pk):
    user = request.user
    artist = Artist.objects.get(pk=artist_pk)
    alerts = Alert.objects.filter(user=user)

    if not user.is_authenticated:
        return redirect('user:login')

    if request.method == "POST":
        title = request.POST.get('title')
        contents = request.POST.get('contents')
        category = request.POST.get('category')
        image = request.FILES.get('image')

        Post.objects.create(
            artist=artist,
            author=user,
            category=category,
            image=image,
            title=title,
            contents=contents,
        )

        # 이용행보 수정
        userWorking = UserWorking.objects.get(user=user, artist=artist)
        userWorking.postRecord += 1
        userWorking.save()

        return redirect('post:post_list', artist_pk=artist.pk, category=category)

    return render(request, 'post/create_post.html', context={'artist':artist, 'alerts':alerts})


# 게시글 수정
def edit_post(request, pk):
    user = request.user
    alerts = Alert.objects.filter(user=user)

    if not user.is_authenticated:
        return redirect('user:login')

    post = get_object_or_404(Post, pk=pk)

    if request.method == "POST":

        category = request.POST.get('category')
        title = request.POST.get('title')
        contents = request.POST.get('contents')
        image = request.FILES.get('image')

        if image is None:
            # 새로운 이미지가 제출되지 않은 경우 기존 이미지 유지
            image = post.image

        # 데이터 변경
        post.title = title
        post.contents = contents
        post.image = image

        post.save()

        return redirect('post:post_list', artist_pk=post.artist.pk, category=category)

    else:
        return render(request, 'post/create_post.html', context={'post': post, 'artist':post.artist, 'alerts':alerts})

# 게시글 삭제
def delete_post(request, pk):
    user = request.user

    if not user.is_authenticated:
        return redirect('user:login')

    if request.method == "GET":
        post = Post.objects.get(pk=pk)
        artist = post.artist
        post.delete()

        # 이용행보 수정
        userWorking = UserWorking.objects.get(user=user, artist=artist)
        userWorking.postRecord -= 1
        userWorking.save()

        return redirect('post:post_list', artist_pk=post.artist.pk, category=post.category)

    return render(request, 'post/failDelete.html')


# 댓글 생성
def create_comment(request, pk):
    user = request.user
    post = Post.objects.get(pk=pk)

    if not user.is_authenticated:
        return redirect('user:login')  # 로그인 페이지 이동

    if request.method == 'POST':
        contents = request.POST.get('contents')

        Comment.objects.create(
            post=post,
            author=user,
            contents=contents
        )

        # 댓글 작성 시 알림 생성
        Alert.objects.create(
            user=post.author,
            artist=post.artist,
            message=user.userName + '님이 ' + post.title + ' 게시글에 댓글을 남겼습니다.'
        )

        # 이용행보 수정
        userWorking = UserWorking.objects.get(user=user, artist=post.artist)
        userWorking.commentRecord += 1
        userWorking.save()

        comments = Comment.objects.filter(post=post)
        return render(request, 'post/post_detail.html', context={'post':post, 'comments':comments})

# 댓글 삭제
def delete_comment(request, pk):
    user = request.user

    if not user.is_authenticated:
        return redirect('user:login')

    if request.method == "GET":
        comment = Comment.objects.get(pk=pk)
        post = comment.post
        comment.delete()

        comments = Comment.objects.filter(post=comment.post)

        # 이용행보 수정
        userWorking = UserWorking.objects.get(user=user, artist=post.artist)
        userWorking.commentRecord -= 1
        userWorking.save()

        return render(request, 'post/post_detail.html', context={'post':comment.post, 'comments':comments})

    return render(request, 'post/failDelete.html')

project/post/views.py
from django.utils import timezone

from alert.models import Alert
from django.shortcuts import render, redirect, get_object_or_404

from artist.models import Artist
from post.models import Post, Comment
from userWorking.models import UserWorking


# 게시글 전체 조회, 카테고리 분류
def post_list(request, artist_pk, category):
    user = request.user
    unread_alerts = Alert.objects.filter(user=user, is_read=False).order_by('-regTime')
    alerts = Alert.objects.filter(user=user)

    if not user.is_authenticated:
        return redirect('user:login')

    artist = Artist.objects.get(pk=artist_pk)
    posts = Post.objects.filter(category=category, artist=artist).order_by('-regTime')


    return render(request, 'post/post_list.html', context={'posts':posts, 'artist':artist, 'alerts':alerts, 'unread_alerts':unread_alerts,'category':category})


# 게시글 상세 조회
def post_detail(request, pk):
    user = request.user
    unread_alerts = Alert.objects.filter(user=user, is_read=False).order_by('-regTime')
    alerts = Alert.objects.filter(user=user)

    if not user.is_authenticated:
        return redirect('user:login')

    if request.method == 'GET':
        post = Post.objects.get(pk=pk)
        comments = Comment.objects.filter(post=post)

        return render(request, 'post/post_detail.html', context={'post':post, 'comments':comments, 'artist':post.artist, 'alerts':alerts, 'unread_alerts':unread_alerts})

# 게시글 생성
def create_post(request, artist_pk):
    user = request.user
    artist = Artist.objects.get(pk=artist_pk)
    unread_alerts = Alert.objects.filter(user=user, is_read=False).order_by('-regTime')
    alerts = Alert.objects.filter(user=user)

    if not user.is_authenticated:
        return redirect('user:login')

    if request.method == "POST":
        title = request.POST.get('title')
        contents = request.POST.get('contents')
        category = request.POST.get('category')
        image = request.FILES.get('image')

        Post.objects.create(
            artist=artist,
            author=user,
            category=category,
            image=image,
            title=title,
            contents=contents,
        )

        # 게시글 작성 시 알림 생성
        Alert.objects.create(
            user=user,
            artist=artist,
            message=F'<{title}> 게시글이 등록되었습니다!',
            regTime=timezone.now()
        )

        # 이용행보 수정
        userWorking = UserWorking.objects.get(user=user, artist=artist)
        userWorking.postRecord += 1
        userWorking.save()

        return redirect('post:post_list', artist_pk=artist.pk, category=category)

    return render(request, 'post/create_post.html', context={'artist':artist, 'alerts':alerts, 'unread_alerts':unread_alerts})


# 게시글 수정
def edit_post(request, pk):
    user = request.user
    unread_alerts = Alert.objects.filter(user=user, is_read=False).order_by('-regTime')
    alerts = Alert.objects.filter(user=user)

    if not user.is_authenticated:
        return redirect('user:login')

    post = get_object_or_404(Post, pk=pk)

    if request.method == "POST":

        category = request.POST.get('category')
        title = request.POST.get('title')
        contents = request.POST.get('contents')
        image = request.FILES.get('image')

        if image is None:
            # 새로운 이미지가 제출되지 않은 경우 기존 이미지 유지
            image = post.image

        # 데이터 변경
        post.category = category
        post.title = title
        post.contents = contents
        post.image = image

        post.save()

        return redirect('post:post_list', artist_pk=post.artist.pk, category=category)

    else:
        return render(request, 'post/modify_post.html', context={'post': post, 'artist':post.artist, 'alerts':alerts, 'unread_alerts':unread_alerts})

# 게시글 삭제
def delete_post(request, pk):
    user = request.user

    if not user.is_authenticated:
        return redirect('user:login')

    if request.method == "GET":
        post = Post.objects.get(pk=pk)
        artist = post.artist
        post.delete()

        # 이용행보 수정
        userWorking = UserWorking.objects.get(user=user, artist=artist)
        userWorking.postRecord -= 1
        userWorking.save()

        return redirect('post:post_list', artist_pk=post.artist.pk, category=post.category)

    return render(request, 'post/failDelete.html')


# 댓글 생성
def create_comment(request, pk):
    user = request.user
    post = Post.objects.get(pk=pk)

    if not user.is_authenticated:
        return redirect('user:login')  # 로그인 페이지 이동

    if request.method == 'POST':
        contents = request.POST.get('contents')

        Comment.objects.create(
            post=post,
            author=user,
            contents=contents
        )

        # 댓글 작성 시 알림 생성
        Alert.objects.create(
            user=post.author,
            artist=post.artist,
            message=user.userName + '님이 <' + post.title + '> 게시글에 댓글을 남겼습니다.',
            regTime = timezone.now()
        )

        # 이용행보 수정
        userWorking = UserWorking.objects.get(user=user, artist=post.artist)
        userWorking.commentRecord += 1
        userWorking.save()

        return redirect('post:post_detail', pk=post.pk)

# 댓글 삭제
def delete_comment(request, pk):
    user = request.user

    if not user.is_authenticated:
        return redirect('user:login')

    if request.method == "GET":
        comment = Comment.objects.get(pk=pk)
        artist = comment.post.artist

        post = comment.post
        comment.delete()

        comments = Comment.objects.filter(post=comment.post)

        # 이용행보 수정
        userWorking = UserWorking.objects.get(user=user, artist=post.artist)
        userWorking.commentRecord -= 1
        userWorking.save()

        return render(request, 'post/post_detail.html', context={'post':comment.post, 'comments':comments, 'artist':artist})

project/post/templates/post/create_post.html
{% extends 'base_artistlist.html' %}
{% with artist=artist alerts=alerts %}
{% load static %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <img class="back" src="{% static 'images/back.png'%}" alt="이전" onclick="goBack()"></img>
    <h1 class="spt_crt_h1" style="margin-right:110px;">게시글 작성하기</h1>
    <h2 class="spt_crt_h2">하고싶은 이야기를 작성해주세요</h2>
    <select class="post-crt-select" name="category" value="{{ post.category }}" >
        <option value="" selected disabled hidden>게시판을 선택해 주세요</option>
        <option value="가수">가수</option>
        <option value="자유">자유</option>
    </select>
    <input class="post-crt-title" type="text" name="title" value="{{ post.title }}" placeholder="클릭하여 제목을 작성해 주세요" required>
    <div style="position: relative; border:none;height:auto; word-break:break-all;">
        <textarea class="post-crt-detail" name="contents" style="padding-top: 15px;" placeholder="클릭하여 내용을 입력해 주세요" required>{{ post.contents }}</textarea>
        <div class="select-wrapper" style="border:none; margin-top:-57px;">
            <!-- <div class="addImg-Button" > -->
                <label for="custom-file" class="custom-addImg-Button">사진</label>
                <input style="display:none" type="file" name="image" value="{{ post.image }}" id="custom-file">
            <!-- </div> -->
        </div>
    </div>
    <button type="submit" class="write-Button" style="background:#b3b1b0" disabled>항목을 모두 작성해 주세요</button>
</form>

<script>
    const title = document.querySelector('.post-crt-title');
    const detail = document.querySelector('.post-crt-detail');
    const select = document.querySelector('.post-crt-select');
    const imageInput = document.querySelector('#custom-file'); // Get the image input element
    const writeButton = document.querySelector('.write-Button');

    function checkInputs() {
        const titleValue = title.value.trim();
        const detailValue = detail.value.trim();
        const selectValue = select.value;
        const imageValue = imageInput.value; // Get the value of the image input

        if (titleValue !== "" && detailValue !== "" && selectValue !== "" && imageValue !== "") {
            writeButton.disabled = false;
            writeButton.style.backgroundColor = "#BC67FF";
            writeButton.innerHTML = "작성하기";
        } else {
            writeButton.disabled = true;
            writeButton.style.backgroundColor = "#b3b1b0";
            writeButton.innerHTML = "항목을 모두 작성해 주세요";
        }
    }

    title.addEventListener("input", checkInputs);
    detail.addEventListener("input", checkInputs);
    select.addEventListener("change", checkInputs);
    imageInput.addEventListener("change", checkInputs); // Listen for changes in the image input

    function goBack() {
        window.history.back();
    }
</script>
{% endblock %}
{% endwith %}

project/post/templates/post/modify_post.html
{% extends 'base_artistlist.html' %}
{% with artist=artist alerts=alerts %}
{% load static %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <img class="back" src="{% static 'images/back.png'%}" alt="이전" onclick="goBack()"></img>
    <h1 class="spt_crt_h1" style="margin-right:110px;" >게시글 수정하기</h1>
    <h2 class="spt_crt_h2">하고싶은 이야기를 작성해주세요</h2>
    <select class="post-crt-select" name="category" value="{{ post.category }}" >
        <option value="" selected disabled hidden>게시판을 선택해 주세요</option>
        <option value="가수">가수</option>
        <option value="자유">자유</option>
    </select>
    <input class="post-crt-title" type="text" name="title" value="{{ post.title }}" placeholder="클릭하여 제목을 작성해 주세요">
    <div style="position: relative; border:none; word-break: break-all;">
        <textarea class="post-crt-detail"  name="contents" style="padding-top: 15px;" placeholder="클릭하여 내용을 입력해 주세요" required>{{ post.contents }}</textarea>
        <div class="select-wrapper" style="border:none; margin-top:-57px;">
            <!-- <div class="addImg-Button" > -->
                <label for="custom-file" class="custom-addImg-Button">사진</label>
                <input style="display:none" type="file" name="image" value="{{ post.image }}" id="custom-file">
            <!-- </div> -->
        </div>
    </div>
    <button type="submit" class="write-Button" style="background:#b3b1b0" disabled>항목을 모두 작성해 주세요</button>
</form>

<script>
    const title = document.querySelector('.post-crt-title');
    const detail = document.querySelector('.post-crt-detail');
    const select = document.querySelector('.post-crt-select');
    const imageInput = document.querySelector('#custom-file'); // Get the image input element
    const writeButton = document.querySelector('.write-Button');

    function checkInputs() {
        const titleValue = title.value.trim();
        const detailValue = detail.value.trim();
        const selectValue = select.value;
        const imageValue = imageInput.value; // Get the value of the image input

        if (titleValue !== "" && detailValue !== "" && selectValue !== "" && imageValue !== "") {
            writeButton.disabled = false;
            writeButton.style.backgroundColor = "#BC67FF";
            writeButton.innerHTML = "작성하기";
        } else {
            writeButton.disabled = true;
            writeButton.style.backgroundColor = "#b3b1b0";
            writeButton.innerHTML = "항목을 모두 작성해 주세요";
        }
    }

    title.addEventListener("input", checkInputs);
    detail.addEventListener("input", checkInputs);
    select.addEventListener("change", checkInputs);
    imageInput.addEventListener("change", checkInputs); // Listen for changes in the image input

    function goBack() {
        window.history.back();
    }
</script>


{% endblock %}
{% endwith %}

project/post/templates/post/post_detail.html
{% extends 'list_base.html' %}
{% load static %}
{% with artist=post.artist alerts=alerts %}
{% block content %}
<div style="  justify-content:row;  display: flex; ">
  <img class="back" src="{% static 'images/back.png'%}" alt="이전" onclick="goBack()"></img>
  <h1 class="post_dtl_h1" style="position: sticky;
    top: 0;
    left: 50%;
    transform: translateX(-50%);">게시판</h1>
</div>
<div class="post-dtl-container">
  <div style="word-break: break-all; height: auto;">
    <div class="post-dtl-title">제목:{{ post.title }}</div>
</div>
        <div class="post-dtl-name">{{ post.author.userName }}</div>
   
    <div style="display: flex; position: row;  ">
      <div class="post-dtl-regTime" >{{ post.regTime|date:"Y.m.d H:i" }}</div>
      {% if request.user == post.author %}
      <form method="get" action="{% url 'post:edit_post' pk=post.pk %}">
        {% csrf_token %}
        <button class="post-modify" ]type="submit">수정</button>
      </form>

      <form method="get" action="{% url 'post:delete_post' pk=post.pk %}">
        {% csrf_token %}
        <button class="post-delete" type="submit" style="margin-left: 3px">
          삭제
        </button>
      </form>
      {% endif %}
    </div>
    
    <div class="post-dtl-line"></div>
        <div class="post-dtl-contents">{{ post.contents }}</div>

    {% if post.image %}
    <div class="post-dtl-img-container">
      <img class="post-dtl-img" src="{{ post.image.url }}" alt="이미지">
    </div>
    {% endif %}

</div>


<div class="post-comment-container">
  <form method="post" action="{% url 'post:create_comment' pk=post.pk %}">
    {% csrf_token %}
   
    <div style="display: flex; margin-left:2px;  ">
        <input class="post-dtl-input" type="text" name="contents" value="{{ comment.contents }}" placeholder="클릭하여 댓글 작성하기">
        <button class="post-dtl-button" type="submit">작성</button>
    </div>
    
  </form>
    {% for comment in comments %}
    <div class="post-comment-box" style="height:auto; word-break:all-break;">
        <div style="display: flex; position: row; margin: 5px 0px 0px 20px;">
            <div>{{ comment.author.userName }}</div>
            <div style="color: #858585; margin-left: 5px;">{{ comment.regTime|date:"Y.m.d H:i" }}</div>
            {% if request.user == comment.author %}
            <form method="get" action="{% url 'post:delete_comment' pk=comment.pk %}">
                {% csrf_token %}
                <button type="submit" style="color: red; margin-left: 30px; font-size:16px;">삭제하기</button>
            </form>
            {% endif %}
        </div>
        <div style="font-size: 20px; margin: -2px 0px 0px 20px; word-break: break-all;">{{ comment.contents }}</div>
    </div>
    {% endfor %}
</div>


<script>
  function goBack() {
    window.history.back();
    }

        </script>

{% endblock %}
{% endwith %}

project/post/templates/post/post_list.html
{% extends 'list_base.html' %}
{% load static%}
{% with artist=artist alerts=alerts %} 
{% block content %}

{% if category == '가수' %}
<div style="margin-bottom: 5px; display: flex; align-items: center;" class="support_list_category">
  <button
  class="allsupport"
    onclick="location.href='{% url 'post:post_list' artist_pk=artist.pk category='가수' %}'"
   type="submit"
   id="all"
   style="width:160px; margin-left:15px; font-size:20px; border-bottom-width: 3px; border-bottom-style: solid; border-bottom-color: black;"
  >

  별의 이야기

</button>
<button
class="mysupport"
type="submit"
onclick="location.href='{% url 'post:post_list' artist_pk=artist.pk category='자유' %}'"
id="my"
style="width:160px; margin-left:24px; font-size:20px;"
>
일상 이야기
</button>
</div>
{% endif %}

{% if category == '자유' %}
<div style="margin-bottom: 5px; display: flex; align-items: center;" class="support_list_category">

  <button
    class="allsupport"
    onclick="location.href='{% url 'post:post_list' artist_pk=artist.pk category='가수' %}'"

    type="submit"
    id="all"
    style="width:160px; margin-left:15px; font-size:20px;"
    >

    별의 이야기
  

  </button>

  <button
    class="mysupport"
    type="submit"

    id="my"
    onclick="location.href='{% url 'post:post_list' artist_pk=artist.pk category='자유' %}'"

    style="width:160px; margin-left:24px; font-size:20px; border-bottom-width: 3px; border-bottom-style: solid; border-bottom-color: black;"
    >
    일상 이야기
  </button>
</div>
{% endif %}

<div class="support_button">
  <div  style="margin-left:285px; margin-top:16px;" >
      <a href="#;" onClick="zoomIn();"><img style="width:20px; height:20px;"src="{% static 'images/zoomin.png'%}" alt="확대"></a>
        <a href="#;" onClick="zoomOut();"><img style="width:20px; height:20px;"src="{% static 'images/zoomout.png'%}" alt="축소"></a>
      </div>
</div>
<div class="post-list-container" style="height: 360px; width: 375px; overflow-y: auto; overflow-x:hidden;">
{% for post in posts %}
  <div class="post-list" onclick="location.href='{% url 'post:post_detail' pk=post.pk%}'">
    <div class="post-title" style=" font-size: 20px;"
      >{{ post.title }}</div
    >
    {% if post.image %}
    <img class="post-img" src="{{ post.image.url }}" />
    {% endif %}
  
      <h2 class="post-name" style="font-size:18px;">작성자 : {{ post.author.userName }}</h2>
      <h1 class="post-time" style="font-size:15px;">{{ post.regTime|date:"Y.m.d H:i" }}</h1>

  </div>
  {% endfor %}
</div>
<form method="get" action="{% url 'post:create_post' artist_pk=artist.pk %}">
  {% csrf_token %}
  <button class="start-Button" style="margin-left: 27px;background: #bc67ff; margin-top:19px; font-size:22px;" onclick="location.href='{% url 'support:create_support' pk=artist.pk %}'">게시글 작성하기</button>

</form>

<script>
<!--window.onload = function() {-->
<!--    // Set an interval to refresh the page every 0.5 seconds (500 milliseconds)-->
<!--    setInterval(function() {-->
<!--        location.reload();-->
<!--    }, 500); // 500 milliseconds (0.5 seconds) interval-->
<!--};-->

</script>

{% endblock %}
{% endwith %}  

project/post/templates/post/post_update.html
{% extends 'base_artistlist.html' %}
{% with artist=artist alerts=alerts %}
{% load static %}
{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <img class="back" src="{% static 'images/back.png'%}" alt="이전" onclick="goBack()"></img>
    <h1 class="spt_crt_h1" >게시글 수정하기</h1>
    <h2 class="spt_crt_h2">내가 작성했던 게시글을 수정해 주세요</h2>
    <select class="post-crt-select" name="category" value="{{ post.category }}" >
        <option value="" selected disabled hidden>게시판을 선택해 주세요</option>
        <option value="가수">가수</option>
        <option value="자유">자유</option>
    </select>
    <input class="post-crt-title" type="text" name="title" value="{{ post.title }}" placeholder="클릭하여 제목을 작성해 주세요">
    <div style="position: relative; border:none;">
        <input class="post-crt-detail" type="textarea" name="contents" value="{{ post.contents }}" style="padding-top: 15px;" placeholder="클릭하여 내용을 입력해 주세요">
        <div class="select-wrapper" style="border:none; margin-top:-50px;">
            <div class="addImg-Button">
                <label for="custom-file" class="custom-addImg-Button">사진</label>
                <input style="display:none" type="file" name="image" value="{{ post.image }}" id="custom-file">
            </div>
        </div>
    </div>
    <button type="submit" class="write-Button" style="background:#b3b1b0" disabled>항목을 모두 작성해 주세요</button>
</form>

<script>
    const form = document.querySelector('form');
    const inputs = form.querySelectorAll('input, select');
    const writeButton = form.querySelector('.write-Button');

    function checkInputs() {
        let allFilled = true;
        inputs.forEach(function (input) {
            if (input.value.trim() === "" || (input.type === 'select-one' && input.selectedIndex === 0)) {
                allFilled = false;
                return;
            }
        });

        if (allFilled) {
            writeButton.disabled = false;
            writeButton.style.backgroundColor = "#BC67FF";
            writeButton.innerHTML = "작성하기";
        } else {
            startButton.disabled = true;
            
        }
    }

    inputs.forEach(function (input) {
        input.addEventListener("input", checkInputs);
    });

    function goBack() {
        window.history.back();
    }
</script>
{% endblock %}
{% endwith %}