artist/urls.py
from django.urls import path

from artist.views import artist_list, select_artist, artist_sns, subscribe_list

app_name = "artist"

urlpatterns = [
    path('<str:category>/', artist_list, name='artist_list'), # 아티스트 조회
    path('<str:category>/subscribe/', subscribe_list, name='subscribe_list'), # 구독한 아티스트 조회
    path('<int:pk>/select/', select_artist, name='select_artist'),  # 아티스트 선택 후 아티스트 정보 페이지 이동
    path('<int:pk>/sns/', artist_sns, name='artist_sns'), # sns 페이지 이동
]

meeting/urls.py
from django.contrib import admin
from django.urls import path
from .views import CreateMeeting, MeetingDtl,MeetingList,closeMeeting,MeetingCloseList,applyMeeting,editMeeting,writedMeetingList,memberStateAccept, memberStateRefusal,applyedMeetingList,subPNList

app_name = "meeting"

urlpatterns = [
    path('<int:artist_id>/',MeetingList, name="MeetingList"),
    path('<int:artist_id>/completed/',MeetingCloseList,name="MeetingCloseList"),
    path('<int:artist_id>/create/', CreateMeeting , name="createMeeting"),
    path('<int:artist_id>/<int:meeting_id>/dtl', MeetingDtl, name='meeting_detail'),
    path('<int:artist_id>/<int:meeting_id>/close/', closeMeeting, name='closeMeeting'),
    path('<int:artist_id>/<int:meeting_id>/apply/', applyMeeting, name='applyMeeting'),
    path('<int:artist_id>/<int:meeting_id>/edit', editMeeting, name='editMeeting'),
    path('<int:artist_id>/write/',writedMeetingList,name='writedMeetingList'),
    path('<int:artist_id>/write/<int:meetingMember_id>/accept',memberStateAccept,name='memberStateAccept'),
    path('<int:artist_id>/write/<int:meetingMember_id>/refusal', memberStateRefusal, name='memberStateRefusal'),
    path('<int:artist_id>/apply/', applyedMeetingList, name='applyedMeetingList'),
    path('<int:artist_id>/phone/', subPNList, name='subPNList'),

]

post/urls.py
from django.urls import path, include

from post.views import post_list, create_post, edit_post, delete_post, post_detail, create_comment, delete_comment

app_name = 'post'

urlpatterns = [
    path('<int:artist_pk>/<str:category>/', post_list, name='post_list'),
    path('create/<int:artist_pk>/', create_post, name='create_post'),
    path('detail/<int:pk>/', post_detail, name='post_detail'),
    path('edit/<int:pk>/', edit_post, name='edit_post'),
    path('deletePost/<int:pk>/', delete_post, name='delete_post'),
    path('createComment/<int:pk>/', create_comment, name='create_comment'),
    path('deleteComment/<int:pk>/', delete_comment, name='delete_comment'),

]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls'), name="main"),
    path('meeting/', include('meeting.urls')),
    path('artist/', include('artist.urls')),
    path('userWorking/', include('userWorking.urls')),
    path('post/', include('post.urls')),
    path('alert/', include('alert.urls')),
    path('support/', include('support.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/user/urls.py
from django.urls import path
from . import views
app_name = "user"

urlpatterns = [
    path("", views.oauth_login, name='login'),
    path("<int:pk>/", views.sign_up, name='signup'),
    path("oauth/", views.Kakao.as_view(), name='oauth'),
    path("oauth/callback/", views.KakaoCallback.as_view()),

    # 튜토리얼 분기
    path("tutorial/", views.tutorial, name='tutorial'),
    path('tutorial/next', views.tutorial_next, name='tutorial_next'),
    path('tutorial/all', views.tutorial_all, name='tutorial_all'),
    path('tutorial/artist', views.tutorial_artist, name='tutorial_artist'),
    path('tutorial/meeting', views.tutorial_meeting, name='tutorial_meeting'),
    path('tutorial/support', views.tutorial_support, name='tutorial_support'),

    # 튜토리얼 아티스트
    path('tutorial/artist-first', views.tutorial_artist_first, name='tutorial_artist_first'),
    path('tutorial/artist-info', views.tutorial_artist_info, name='tutorial_artist_info'),
    path('tutorial/subscribe-list', views.tutorial_subscribe_artist, name='tutorial_subscribe_artist'),
    path('tutorial/artist-list', views.tutorial_artist_list, name='tutorial_artist_list'),

    # 튜토리얼 모임
    path('tutorial/meeting-first', views.tutorial_meeting_first, name='tutorial_meeting_first'),
    path('tutorial/meeting-manage', views.tutorial_meeting_manage, name='tutorial_meeting_manage'),
    path('tutorial/meeting-start',views.tutorial_meeting_start, name='tutorial_meeting_start'),
    path('tutorial/meeting-wirte', views.tutorial_meeting_writed, name='tutorial_meeting_writed'),
    path('tutorial/meeting-wirte-2', views.tutorial_meeting_writed_2, name='tutorial_meeting_writed_2'),
    path('tutorial/meeting-userWorking', views.tutorial_meeting_userWorking, name='tutorial_meeting_userWorking'),
    path('tutorial/meeting-apply', views.tutorial_meeting_apply, name='tutorial_meeting_apply'),
    path('tutorial/meeting-pn', views.tutorial_meeting_pn, name='tutorial_meeting_pn'),
    path('tutorial/meeting-list', views.tutorial_meeting_list, name='tutorial_meeting_list'),
    path('tutorial/meeting-list-2',views.tutorial_meeting_list2,name='tutorial_meeting_list2'),

    # 튜토리얼 서포트
    path('tutorial/support-first', views.tutorial_support_first, name='tutorial_support_first'),
    # 서포트 참여
    path('tutorial/support-join', views.tutorial_support_join_list, name='tutorial_support_join'),
    path('tutorial/support-join-form', views.tutorial_support_join_form, name='tutorial_support_join_form'),
    path('tutorial/support-join-detail-1', views.tutorial_support_join_detail_1, name='tutorial_support_join_detail_1'),
    path('tutorial/support-join-detail-2', views.tutorial_support_join_detail_2, name='tutorial_support_join_detail_2'),
    # 서포트 생성
    path('tutorial/support-start', views.tutorial_support_start, name='tutorial_support_start'),
    path('tutorial/support-start-form', views.tutorial_support_start_form, name='tutorial_support_start_form'),
    path('tutorial/support-start-step-1', views.tutorial_support_start_step_1, name='tutorial_support_start_step_1'),
    path('tutorial/support-start-step-2', views.tutorial_support_start_step_2, name='tutorial_support_start_step_2'),
    path('tutorial/support-start-step-3', views.tutorial_support_start_step_3, name='tutorial_support_start_step_3'),
    path('tutorial/support-start-step-4', views.tutorial_support_start_step_4, name='tutorial_support_start_step_4'),
    # 서포트 관리
    path('tutorial/support-manage', views.tutorial_support_manage, name='tutorial_support_manage'),
    path('tutorial/support-manage-detail-1', views.tutorial_support_manage_detail_1, name='tutorial_support_manage_detail_1'),
    path('tutorial/support-manage-detail-2', views.tutorial_support_manage_detail_2, name='tutorial_support_manage_detail_2'),
    path('tutorial/support-start', views.tutorial_support_start, name='tutorial_support_start'),

    ]

support/urls.py
from django.urls import path
from support.views import support_list, create_support, support_list_complete, support_dtl, create_support_form, \
    my_support_list, my_support_list_complete

app_name = "support"

urlpatterns = [
    # 전체목록
    path('<int:pk>/posts/', support_list, name='support_list'),
    path('<int:pk>/posts/complete/', support_list_complete, name='support_list_complete'),
    path('<int:pk>/my/', my_support_list, name='my_support_list'),
    path('<int:pk>/my/complete/', my_support_list_complete, name='my_support_list_complete'),
    # 생성
    path('<int:pk>/new/', create_support, name='create_support'),
    # 상세보기
    path('<int:pk>/post/<int:spt_pk>/', support_dtl, name='support_dtl'),
    # 수정
    # 삭제
    # 모금정보 작성
    path('<int:pk>/post/<int:spt_pk>/form/', create_support_form, name='create_support_form')
]

user/urls.py
from django.urls import path
from .views import oauth_login, Kakao, KakaoCallback, sign_up, tutorial

app_name = "user"

urlpatterns = [
    path("", oauth_login, name='login'),
    path("<int:pk>/", sign_up, name='signup'),
    path("oauth/", Kakao.as_view(), name='oauth'),
    path("oauth/callback/", KakaoCallback.as_view()),
    path("tutorial/", tutorial, name='tutorial'),
]

post/models.py
from enum import Enum
from django.utils import timezone

from django.db import models

from artist.models import Artist

from user.models import User


class Category(Enum):
    가수 = '가수'
    자유 = '자유'

class Post(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.CharField(max_length=10, choices=[(status.value, status.name) for status in Category], default=Category.가수.value)

    image = models.ImageField(null=True)
    title = models.CharField(max_length=50)
    contents = models.TextField(max_length=1000)
    regTime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    contents = models.TextField(max_length=200)
    regTime = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.post.title

user/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

from artist.models import Artist

class UserManager(BaseUserManager):
    def create_user(self, kakaoId, userName, age, gender, password=None, **extra_fields):
        user = self.model(
            kakaoId=kakaoId,
            userName=userName,
            age=age,
            gender=gender
        )
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        user.set_password(password)
        user.is_active = True
        user.save()
        return user

    def create_superuser(self, kakaoId, userName, password=None, **extra_fields):
        superuser = self.create_user(
            kakaoId=kakaoId,
            userName=userName,
            age=999,
            gender='none',
            password=password
        )
        superuser.is_admin = True
        superuser.is_superuser = True
        superuser.is_active = True
        superuser.is_staff = True
        superuser.save()
        return superuser

# Create your models here.
class User(AbstractBaseUser, PermissionsMixin):
    kakaoId=models.CharField(max_length=100, unique=True)
    userName=models.CharField(max_length=100)
    age=models.IntegerField(null=True)
    gender=models.CharField(max_length=10, null=True)
    phoneNumberRegex = RegexValidator(regex=r'^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$')
    phoneNumber = models.CharField(validators=[phoneNumberRegex], max_length=11, unique=True, null=True)
    subPhoneNumber=models.CharField(null=True, validators=[phoneNumberRegex], max_length=11)
    region=models.CharField(null=True, max_length=20)
    artists=models.ManyToManyField(Artist)

    is_staff = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'kakaoId'
    REQUIRED_FIELDS = ['userName']

    def __str__(self):
        return self.userName

user/views.py
from alert.models import Alert
from django.contrib.auth import login, authenticate
from django.utils import timezone
from django.shortcuts import render,redirect
from django.views.generic import View, CreateView, UpdateView, DeleteView

from .models import User
from artist.models import Artist
import requests

uri = "http://127.0.0.1:8000"

# 로그인 템플릿
def oauth_login(request):
    return render(request, './user/login.html', {"title":"Main"})

# 회원가입 상세정보 입력
def sign_up(request, pk):
    if not request.user.pk == pk:
        return redirect('user:login')
    if request.method=='GET':
        user = User.objects.get(pk=pk)
        return render(request, './user/signup.html', {"user":user})
    elif request.method=='POST':
        user = request.user
        user.age=request.POST.get('age')
        user.phoneNumber=request.POST.get('phoneNumber')
        user.subPhoneNumber=request.POST.get('subPhoneNumber')
        user.region=request.POST.get('region')
        user.save()

        return redirect('user:tutorial')

# 아티스트선택/튜토리얼 분기 페이지
def tutorial(request):
    return render(request, './user/tutorial.html')

# 인가 코드 요청
class Kakao(View):
    def get(self, request):
        kakao_api="https://kauth.kakao.com/oauth/authorize?response_type=code"
        redirect_uri=f"{uri}/oauth/callback"
        client_id="714db211a2aee35b2ed21cfed611dd34"
        return redirect(f"{kakao_api}&client_id={client_id}&redirect_uri={redirect_uri}")

# 토큰 발급 및 회원가입
class KakaoCallback(View):
    def get(self, request):
        data = {
            "grant_type":"authorization_code",
            "client_id":"714db211a2aee35b2ed21cfed611dd34",
            "redirection_uri":f"{uri}/users/oauth",
            "code":request.GET["code"]
        }
        kakao_token_api="https://kauth.kakao.com/oauth/token"
        access_token = requests.post(kakao_token_api, data=data).json().get("access_token")
        #카카오 사용자 정보 요청
        kakao_user_api="https://kapi.kakao.com/v2/user/me"
        user_info=requests.get(kakao_user_api, headers={"Authorization":f"Bearer ${access_token}"}).json()
        # print(user_info)
        if not User.objects.filter(kakaoId=user_info['id']).exists():
            if user_info['kakao_account']['gender']:
                user = User.objects.create(
                    kakaoId=user_info['id'],
                    userName=user_info['properties']['nickname'],
                    gender=user_info['kakao_account']['gender'],
                    last_login=timezone.now(),
                    password="1234",
                )
            else:
                user = User.objects.create(
                    kakaoId=user_info['id'],
                    userName=user_info['properties']['nickname'],
                    last_login=timezone.now(),
                    password="1234",
                )
            return redirect('user:signup', pk=user.pk)
        # 로그인
        user = User.objects.get(kakaoId=user_info['id'])
        login(request, user, 'user.auth.MyBackend')

        if user.artists.all(): # 구독한 아티스트가 있다면 구독 아티스트로 이동
            return redirect('artist:subscribe_list', category='none')
        else: # 첫 사용자라면 아티스트 전체조회로 이동
            return redirect('artist:artist_list', category='none')

project/user/templates/tutorial_meeting/apply_new.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no" />

    <link rel="stylesheet" href="{% static 'css/base_meeting.css' %}" />
    <link rel="stylesheet" href="{% static 'css/header.css' %}" />
    <link rel="stylesheet" href="{% static 'css/footer.css' %}" />
    <link rel="stylesheet" href="{% static 'css/meeting_list.css' %}" />
    <link rel="stylesheet" href="{% static 'css/meeting_detail.css' %}?after" />
    <link rel="stylesheet" href="{% static 'css/writed_meeting_list.css' %}" />
    <link rel="stylesheet" href="{% static 'css/meeting_completed_list.css' %}" />
    <link rel="stylesheet" href="{% static 'css/applyed_meeting_list.css' %}" />
    <link rel="stylesheet" href="{% static 'css/support_list.css' %}?after" />
    <link rel="stylesheet" href="{% static 'css/support_form.css' %}?after" />
    <link rel="stylesheet" href="{% static 'css/artist_info.css' %}?after" />


    {% include 'head.html' %}
    <style>
      .dark-background {
       background-color: rgba(0, 0, 0, 0.6);
       position: absolute;
       top: 0;
       left: 0;
       width: 375px;
       height: 100vh;
       z-index: 2;
       display: flex;
       align-items: center;
       justify-content: center;
     }
   
     #hidden-pointer {
       display: none;
       position: absolute;
       animation: motion 1s linear infinite alternate;
     }
   
     @keyframes motion {
       0% {
         top: 26%;
       }
       100% {
         top: 28%;
       }
     }
     </style>
   </head>
  <body>

<div class="container" style="position:relative">
    <div class="dark-background" id="popup" style="display:none;">
     </div>
    <div class="header ">
      <form>
        <button class="btn-select" type="submit">
          &nbsp; &nbsp;임영웅 •••
        </button>
      </form>
      <div class="icon">
        <form>
          <button type="submit">
            <img
              class="user"
              src="{% static 'images/user.png'%}"
              alt="이용행보"
            />
          </button>
        </form>
        <form>
          <button id="alarm-button">
            <img
              class="alarm"
              src="{% static 'images/alarm.png'%}"
              alt="알람"
            />
          </button>
        </form>
      </div>
    </div>
    <div class="content">

<div style="margin-bottom: 5px; display: flex; align-items: center;" class="support_list_category">
    <button class ="allsupport" style="width:160px; margin-left:15px; font-size:20px;" onclick="location.href='{% url 'meeting:MeetingList' artist_id=artist.id %}'">모임 전체</button>
    <button class ="mysupport" style="width:160px; margin-left:24px; font-size:20px;border-bottom:3px solid #000000;" onclick="location.href='{% url 'meeting:writedMeetingList' artist_id=artist_id  %}'">나의 모임</button>
</div>

    <div class="meeting-button">
        <button   onclick="location.href='{%url 'meeting:writedMeetingList' artist_id=artist_id  %}'">작성</button>
        <button style=" border: 1px solid #bc67ff;color:#bc67ff;" onclick="location.href='{%url 'meeting:applyedMeetingList' artist_id=artist_id  %}'">신청</button>
    <button onclick="location.href='{%url 'meeting:subPNList' artist_id=artist_id  %}'">보호자</button>
    <div  style="margin-left:285px; margin-top:-25px;" >
        <a href="#;" onClick="zoomIn();"><img style="width:20px; height:20px;"src="{% static 'images/zoomin.png'%}" alt="확대"></a>
          <a href="#;" onClick="zoomOut();"><img style="width:20px; height:20px;"src="{% static 'images/zoomout.png'%}" alt="축소"></a>
        </div>    
    </div>

    <form class="meeting-search-form" method="get" action="{% url 'meeting:applyedMeetingList' artist_id=artist_id %}">
        <label for="searchInput" style="font-size:17px;">모임 검색:</label>
        <input type="text" id="searchInput" name="search" placeholder="내 신청 모임명을 검색하세요"style="text-indent:0px; width:182px;">
        <button type="submit" style="margin-left:-1px;" >검색</button>
    </form>
    <div class="meeting-writed">
        <div class="writed-lost">
          <div class="member-info">
            <h3>내가 신청한 모임명 1</h3>
          </div>
          <p><span class="date-color">2023/8/18</span>에 신청했습니다.</p>
          <p>현재 <span class="wait">대기 </span> 상태입니다.</p>
        </div>
        <div class="writed-lost">
          <div class="member-info">
            <h3>내가 신청한 모임명 2</h3>
          </div>
          <p><span class="date-color">2023/8/18</span>에 신청했습니다.</p>
          <p>현재 <span class="approval"> 승인 </span> 상태입니다. 알림을 확인하세요</p>
        </div>
        <div class="writed-lost">
          <div class="member-info">
            <h3>내가 신청한 모임명 3</h3>
          </div>
          <p><span class="date-color">2023/8/18</span>에 신청했습니다.</p>
          <p>현재<span class="reject"> 거부 </span> 상태입니다. 다른 모임을 찾아보세요</p>
        </div>
      </div>

    </div>
    <div class="footer">
        <div class="singer" onclick="location.href='{% url 'artist:select_artist' pk=artist.pk %}'">
            <img id="singer-img" src="{% static 'images/singer.png'%}" alt="가수 이미지"></img>
          <div class="label" >내 가수</div>
        </div>
        <div class="list"  onclick="location.href='{% url 'post:post_list' artist_pk=artist.pk category='가수' %}'">
            <img id="list-img" src="{% static 'images/list.png'%}" alt="게시글 이미지"></img>
            <div class="label">게시판</div>
        </div>
        <div class="group"  onclick="location.href='{% url 'meeting:MeetingList' artist_id=artist.id %}'">
            <img id="group-img" style="width:58px; height:58px; margin-top:-6px;"src="{% static 'images/purplegroup.png'%}" alt="그룹 이미지" ></img>
          <div class="label" style="margin-top:-1px;color:#BC67FF">모임</div>
        </div>
        <div class="support" onclick="location.href='{% url 'support:support_list' pk=artist.pk %}'">
            <img id="support-img" style="width:60px; height:60px;margin-top:-5px;margin-left:-14px;"src="{% static 'images/support.png'%}" alt="서포트 이미지" ></img>
          <div class="label"style="margin-top:-3px;margin-left:-15px;">서포트</div>
        </div>
    
      </div>
    
 </div>

</body>
</html>

project/user/templates/tutorial_meeting/tutorial_meeting_start.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no" />
    <link rel="stylesheet" href="{% static 'css/base_form.css' %}" />
    <link rel="stylesheet" href="{% static 'css/meeting_create.css' %}" />
    <link rel="stylesheet" href="{% static 'css/meeting_edit.css' %}" />




      <title>별너울</title>
    {% include 'head.html' %}
    <style>
      .dark-background {
        background-color: rgba(0, 0, 0, 0.6);
        position: absolute;
        top: 0;
        left: 0;
        width: 375px;
        height: 100vh;
        z-index: 5;
        display: flex;
        align-items: center;
        justify-content: center;
      }
    </style>
   </head>
  <body>
    <div class="container" style="position:relative">
      <div class="dark-background" id="popup" style="display:none;">
      </div>

      <div class="content">
        <img id="hidden-img" src="{% static 'tutorial/meet_step2_2.png' %}"
        style=" width: 260px; display: none; position: absolute; z-index: 9999; top: 17%; left: 50%; transform: translate(-50%, -50%);"
        alt="이미지">
    <img class="back" src="{% static 'images/back.png'%}" alt="이전" onclick="goBack()"></img>
      <h1 class="h1-meeting">모임 작성하기</h1>
      <h3 class="h3-meeting">등록하고 싶은 모임 세부 사항을 작성해요!</h3>

      <form class="register input" style="position: relative;" id="meetingForm" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <label for="id_title" class="name" ></label>
        <input type="text" name="title" id="id_title" placeholder="모임명" required>

        <label for="id_location" class="place"></label>
        <input type="text" name="location" id="id_location" placeholder="장소" required>


        <input data-placeholder="일시"
        required
        aria-required="true"
        value={startDateValue}
        className={styles.selectDay}
        onChange={StartDateValueHandler}
         class="date-placeholder" type="date" name="meetDate" id="id_meetDate" placeholder="일시" required>

        <label for="id_age" class="age"></label>
        <input type="text" name="age" id="id_age" placeholder="나이제한" required>

        <label for="id_peopleNm" class="people"></label>
        <input type="number" name="peopleNm" id="id_peopleNm" placeholder="인원" required>

        <label for="id_kakaoLink" class="openkakao"></label>
        <input type="text" name="kakaoLink" id="id_kakaoLink" placeholder="오픈 채팅방 링크" required>

        <div style="position: relative; border:none;">
        <label for="id_body"></label>
        <textarea style="position: relative;" class="detail1" name="body" id="id_body" placeholder="내용"required></textarea>
        <div class="select-wrapper " style="border:none; margin-top:-50px;">

        <label style="position: relative;" for="id_image" class="addImg-Button">사진</label>
        <input type="file" name="image" id="id_image" style="display:none" required>
        </div>
        </div>
      </form>
      <div>
        <input type="submit" value="항목을 모두 작성해 주세요" class="register-Button" disabled style="border-radius: 30.5px; position: relative; background: #b3b1b0">
      </div>

<!-- JavaScript 부분을 아래와 같이 변경합니다 -->
<script>
  let inputs = document.querySelectorAll("input");
  let startButton = document.querySelector(".register-Button");
  startButton.disabled = true;

  function checkInputs() {
    let allFilled = true;
    inputs.forEach(function (input) {
      if (input.value === "") {
        allFilled = false;
        return;
      }
    });

    if (allFilled) {
      startButton.disabled = false;
      startButton.style.backgroundColor = "#BC67FF";
      startButton.value = "작성하기";
    } else {
      startButton.disabled = true;
      startButton.style.backgroundColor = "#b3b1b0";
      startButton.value = "항목을 모두 작성해 주세요";
    }
  }

  inputs.forEach(function (input) {
    input.addEventListener("input", checkInputs);
  });

  startButton.addEventListener("click", function () {
    if (!startButton.disabled) {
      // 여기서 tutorial_meeting 페이지로 이동하도록 리다이렉션 수행
      window.location.href = "{% url 'user:tutorial_meeting' %}";
    }
  });

  function goBack() {
    window.history.back();
  }

  const content = document.querySelector('.content');
  const popup = document.getElementById("popup"); //배경 어둡게 
    const form = document.querySelector('form'); //보여주고 싶은 영역
    const text = document.querySelector('textarea'); //보여주고 싶은 영역
    const label = document.querySelector('label'); //보여주고 싶은 영역
    const button = document.querySelector('.register-Button'); //보여주고 싶은 영역
    const hiddenImg = document.getElementById("hidden-img"); // 이미지 요소 추가
    const image = document.querySelector('.addImg-Button'); //보여주고 싶은 영역
    const wrapper = document.querySelector('.select-wrapper'); //보여주고 싶은 영역
    const initialScrollPosition = content.scrollTop;

    setTimeout(function () { 
        popup.style.display = "block";
        label.style.zIndex = "9990";
        form.style.zIndex = "9990";
        text.style.zIndex = "9990";
        button.style.zIndex = "9990";
        image.style.zIndex = "9990";
        wrapper.style.zIndex = "9990";
        hiddenImg.style.display = "block";
        content.scrollTop = initialScrollPosition;
    }, 1000);
</script>

      </div>

  </div>

</body>
</html>