meeting/urls.py
from django.contrib import admin
from django.urls import path
from .views import CreateMeeting, MeetingDtl,MeetingList,closeMeeting,MeetingCloseList,applyMeeting,editMeeting,writedMeetingList,memberStateAccept, memberStateRefusal,applyedMeetingList,subPNList

app_name = "meeting"

urlpatterns = [
    path('<int:artist_id>/',MeetingList, name="MeetingList"),
    path('<int:artist_id>/completed/',MeetingCloseList,name="MeetingCloseList"),
    path('<int:artist_id>/create/', CreateMeeting , name="createMeeting"),
    path('<int:artist_id>/<int:meeting_id>/dtl', MeetingDtl, name='meeting_detail'),
    path('<int:artist_id>/<int:meeting_id>/close/', closeMeeting, name='closeMeeting'),
    path('<int:artist_id>/<int:meeting_id>/apply/', applyMeeting, name='applyMeeting'),
    path('<int:artist_id>/<int:meeting_id>/edit', editMeeting, name='editMeeting'),
    path('<int:artist_id>/write/',writedMeetingList,name='writedMeetingList'),
    path('<int:artist_id>/write/<int:meetingMember_id>/accept',memberStateAccept,name='memberStateAccept'),
    path('<int:artist_id>/write/<int:meetingMember_id>/refusal', memberStateRefusal, name='memberStateRefusal'),
    path('<int:artist_id>/apply/', applyedMeetingList, name='applyedMeetingList'),
    path('<int:artist_id>/phone/', subPNList, name='subPNList'),

]

post/urls.py
from django.urls import path, include

from post.views import post_list, create_post, edit_post, delete_post, post_detail, create_comment, delete_comment

app_name = 'post'

urlpatterns = [
    path('<int:artist_pk>/<str:category>/', post_list, name='post_list'),
    path('create/<int:artist_pk>/', create_post, name='create_post'),
    path('detail/<int:pk>/', post_detail, name='post_detail'),
    path('edit/<int:pk>/', edit_post, name='edit_post'),
    path('deletePost/<int:pk>/', delete_post, name='delete_post'),
    path('createComment/<int:pk>/', create_comment, name='create_comment'),
    path('deleteComment/<int:pk>/', delete_comment, name='delete_comment'),

]

project/meeting/urls.py
from django.contrib import admin
from django.urls import path
from .views import CreateMeeting, MeetingDtl,MeetingList,closeMeeting,MeetingCloseList,applyMeeting,editMeeting,writedMeetingList,memberStateAccept, memberStateRefusal,applyedMeetingList,subPNList, MeetingList_tutorial

app_name = "meeting"

urlpatterns = [
    path('<int:artist_id>/',MeetingList, name="MeetingList"),
    path('<int:artist_id>/completed/',MeetingCloseList,name="MeetingCloseList"),
    path('<int:artist_id>/create/', CreateMeeting , name="createMeeting"),
    path('<int:artist_id>/<int:meeting_id>/dtl', MeetingDtl, name='meeting_detail'),
    path('<int:artist_id>/<int:meeting_id>/close/', closeMeeting, name='closeMeeting'),
    path('<int:artist_id>/<int:meeting_id>/apply/', applyMeeting, name='applyMeeting'),
    path('<int:artist_id>/<int:meeting_id>/edit', editMeeting, name='editMeeting'),
    path('<int:artist_id>/write/',writedMeetingList,name='writedMeetingList'),
    path('<int:artist_id>/write/<int:meetingMember_id>/accept',memberStateAccept,name='memberStateAccept'),
    path('<int:artist_id>/write/<int:meetingMember_id>/refusal', memberStateRefusal, name='memberStateRefusal'),
    path('<int:artist_id>/apply/', applyedMeetingList, name='applyedMeetingList'),
    path('<int:artist_id>/phone/', subPNList, name='subPNList'),
    path('<int:artist_id>/tutorial/', MeetingList_tutorial, name =' MeetingList_tutorial'),

]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls'), name="main"),
    path('meeting/', include('meeting.urls')),
    path('artist/', include('artist.urls')),
    path('userWorking/', include('userWorking.urls')),
    path('post/', include('post.urls')),
    path('alert/', include('alert.urls')),
    path('support/', include('support.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/user/urls.py
from django.urls import path
from . import views
app_name = "user"

urlpatterns = [
    path("", views.oauth_login, name='login'),
    path("<int:pk>/", views.sign_up, name='signup'),
    path("oauth/", views.Kakao.as_view(), name='oauth'),
    path("oauth/callback/", views.KakaoCallback.as_view()),

    # 튜토리얼 분기
    path("tutorial/", views.tutorial, name='tutorial'),
    path('tutorial/next', views.tutorial_next, name='tutorial_next'),
    path('tutorial/all', views.tutorial_all, name='tutorial_all'),
    path('tutorial/artist', views.tutorial_artist, name='tutorial_artist'),
    path('tutorial/meeting', views.tutorial_meeting, name='tutorial_meeting'),
    path('tutorial/support', views.tutorial_support, name='tutorial_support'),

    # 튜토리얼 아티스트
    path('tutorial/artist-first', views.tutorial_artist_first, name='tutorial_artist_first'),
    path('tutorial/artist-info', views.tutorial_artist_info, name='tutorial_artist_info'),
    path('tutorial/subscribe-list', views.tutorial_subscribe_artist, name='tutorial_subscribe_artist'),
    path('tutorial/artist-list', views.tutorial_artist_list, name='tutorial_artist_list'),

    # 튜토리얼 모임
    path('tutorial/meeting-first', views.tutorial_meeting_first, name='tutorial_meeting_first'),
    path('tutorial/meeting-manage', views.tutorial_meeting_manage, name='tutorial_meeting_manage'),
    path('tutorial/meeting-start',views.tutorial_meeting_start, name='tutorial_meeting_start'),
    path('tutorial/meeting-wirte', views.tutorial_meeting_writed, name='tutorial_meeting_writed'),
    path('tutorial/meeting-wirte-2', views.tutorial_meeting_writed_2, name='tutorial_meeting_writed_2'),
    path('tutorial/meeting-userWorking', views.tutorial_meeting_userWorking, name='tutorial_meeting_userWorking'),
    path('tutorial/meeting-apply', views.tutorial_meeting_apply, name='tutorial_meeting_apply'),
    path('tutorial/meeting-pn', views.tutorial_meeting_pn, name='tutorial_meeting_pn'),
    path('tutorial/meeting-list', views.tutorial_meeting_list, name='tutorial_meeting_list'),
    path('tutorial/meeting-list-2',views.tutorial_meeting_list2,name='tutorial_meeting_list2'),

    # 튜토리얼 서포트
    path('tutorial/support-first', views.tutorial_support_first, name='tutorial_support_first'),
    # 서포트 참여
    path('tutorial/support-join', views.tutorial_support_join_list, name='tutorial_support_join'),
    path('tutorial/support-join-form', views.tutorial_support_join_form, name='tutorial_support_join_form'),
    path('tutorial/support-join-detail-1', views.tutorial_support_join_detail_1, name='tutorial_support_join_detail_1'),
    path('tutorial/support-join-detail-2', views.tutorial_support_join_detail_2, name='tutorial_support_join_detail_2'),
    # 서포트 생성
    path('tutorial/support-start', views.tutorial_support_start, name='tutorial_support_start'),
    path('tutorial/support-start-form', views.tutorial_support_start_form, name='tutorial_support_start_form'),
    path('tutorial/support-start-step-1', views.tutorial_support_start_step_1, name='tutorial_support_start_step_1'),
    path('tutorial/support-start-step-2', views.tutorial_support_start_step_2, name='tutorial_support_start_step_2'),
    path('tutorial/support-start-step-3', views.tutorial_support_start_step_3, name='tutorial_support_start_step_3'),
    path('tutorial/support-start-step-4', views.tutorial_support_start_step_4, name='tutorial_support_start_step_4'),
    # 서포트 관리
    path('tutorial/support-manage', views.tutorial_support_manage, name='tutorial_support_manage'),
    path('tutorial/support-manage-detail-1', views.tutorial_support_manage_detail_1, name='tutorial_support_manage_detail_1'),
    path('tutorial/support-manage-detail-2', views.tutorial_support_manage_detail_2, name='tutorial_support_manage_detail_2'),
    path('tutorial/support-start', views.tutorial_support_start, name='tutorial_support_start'),

    ]

project/userWorking/urls.py
from django.urls import path

from userWorking.views import show_userWorking,show_userWorking_guest

app_name = "userWorking"

urlpatterns = [
    path('<int:pk>/', show_userWorking, name='show_userWorking'),
    path('<int:pk>/<int:meetingMember_id>/', show_userWorking_guest, name='show_userWorking_guest'),

]

meeting/models.py
from django.db import models
from enum import Enum
from user.models import User
from artist.models import Artist

# 미팅 모집 상태
class MeetingState (Enum):
    모집중 = '모집중'
    파토 = '파토'
    모집완료 = '모집완료'

#미팅 멤버 신청 상태
class MemberState(Enum):
    대기 = '대기'
    승인 = '승인'
    거부 = '거부'

# Create your models here.
class Meeting(models.Model):
    title = models.CharField(max_length=50) #제목
    body = models.TextField() #본문
    meetDate = models.DateField() #일시
    writeDate = models.DateTimeField(auto_now=True) #작성시간
    location = models.CharField(max_length=50) #장소
    age = models.CharField(max_length=10) #나이제한
    peopleNm = models.IntegerField() #인원
    kakaoLink = models.URLField() #카카오채팅방링크
    meetingState = models.CharField(max_length=20, choices=[(status.value, status.name) for status in MeetingState], default=MeetingState.모집중.value) #모집 상태
    image = models.ImageField(upload_to='meeting_images/', null=True, blank=True) #사진첨부
    writeUser = models.ForeignKey(User, on_delete=models.CASCADE,null=True) #작성자
    artist = models.ForeignKey(Artist, related_name="artist_meetings", on_delete=models.CASCADE)

class MeetingMember(models.Model):
    Meeting = models.ForeignKey(Meeting, related_name="members", on_delete=models.CASCADE, null=True) #참가미팅
    User = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    writeDate = models.DateTimeField(auto_now=True)  # 작성시간
    memberState = models.CharField(max_length=20, choices=[(status.value, status.name) for status in MemberState], default = MemberState.대기.value)
    def __str__(self):
        return self.User.userName

meeting/forms.py
from django import forms
from .models import Meeting

class MeetingEditForm(forms.ModelForm):
    class Meta:
        model = Meeting
        fields = ['title', 'body', 'meetDate', 'location', 'age', 'peopleNm', 'kakaoLink', 'image']

meeting/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Meeting, MeetingMember, MeetingState, MemberState
from artist.models import Artist
from .forms import MeetingEditForm
from alert.models import Alert


#모임 생성
def CreateMeeting(request, artist_id):
    artist =get_object_or_404(Artist, pk=artist_id)
    user = request.user
    alerts = Alert.objects.filter(user=user)

    if request.method == 'POST' :
        meeting = Meeting()
        meeting.title = request.POST['title']
        meeting.body = request.POST['body']
        meeting.meetDate = request.POST['meetDate']
        meeting.location = request.POST['location']
        meeting.age = request.POST['age']
        meeting.peopleNm = request.POST['peopleNm']
        meeting.kakaoLink = request.POST['kakaoLink']
        meeting.image = request.FILES['image']
        meeting.writeUser = request.user
        meeting.artist = artist
        meeting.save()
        return redirect('meeting:MeetingList', artist_id=artist_id)

    return render(request, "html/meeting_create.html", {'artist': artist, 'alerts': alerts})

#모임 각각 상세조회
def MeetingDtl(request, artist_id, meeting_id):
    artist =get_object_or_404(Artist, pk=artist_id)
    user = request.user
    alerts = Alert.objects.filter(user=user)
    meeting = get_object_or_404(Meeting, pk=meeting_id)
    if meeting.writeUser == request.user:
        return render(request, "html/meeting_detail_admin.html", {'meeting': meeting, 'alerts':alerts, 'artist': artist})
    return render(request, "html/meeting_detail.html", {'meeting': meeting, 'alerts': alerts, 'artist': artist})

#모집 중인 모임 목록
def MeetingList(reqeust, artist_id):
    user = reqeust.user
    artists = user.artists.all()
    artist =get_object_or_404(Artist, pk=artist_id)
    meetings = artist.artist_meetings.all()
    meetings_recruiting = meetings.filter(meetingState=MeetingState.모집중.value)
    alerts = Alert.objects.filter(user=user)

    context = {
        'meetings_recruiting': meetings_recruiting,
        'artist_id': artist_id,
        'artist': artist,
        'artists' : artists,
        'alerts' : alerts
    }
    return render(reqeust, "html/meeting_list.html", context)

#모집 완료된 모임 목록
def MeetingCloseList(reqeust, artist_id):
    user = reqeust.user
    alerts = Alert.objects.filter(user=user)
    artists = Artist.objects.all()
    artist =get_object_or_404(Artist, pk=artist_id)
    meetings = artist.artist_meetings.all()
    meetings_completed = meetings.filter(meetingState=MeetingState.모집완료.value)
    meetings_recruiting = meetings.filter(meetingState=MeetingState.모집중.value)

    context = {
        'meetings_recruiting': meetings_recruiting,
        'meetings_completed': meetings_completed,
        'artist_id': artist_id,
        'artist': artist,
        'artists' : artists,
        'alerts' : alerts,
    }
    return render(reqeust, "html/meeting_completed_list.html", context)

#모임 상태 모집 완료로 바꾸기
def closeMeeting(request, meeting_id, artist_id):
    user = request.user
    alerts = Alert.objects.filter(user=user)
    artist = get_object_or_404(Artist, pk=artist_id)
    meeting = get_object_or_404(Meeting, id=meeting_id)
    meeting.meetingState = MeetingState.모집완료.value
    meeting.save()
    return redirect('meeting:meeting_detail', meeting_id=meeting_id, artist_id=artist_id)

#모임 신청
def applyMeeting(request, meeting_id, artist_id):
    user = request.user
    alerts = Alert.objects.filter(user=user)
    artist = get_object_or_404(Artist, pk=artist_id)
    meeting = get_object_or_404(Meeting, id=meeting_id)
    meetingMember=MeetingMember.objects.create(User=user, Meeting = meeting)
    meeting_members = meeting.members.all()
    print(meeting_members)
    meetingMember.save()
    meeting.save()
    context = {
        'meeting_id': meeting_id,
        'alerts' : alerts,
        'artist' : artist
    }
    return redirect('meeting:meeting_detail', meeting_id=meeting_id, artist_id=artist_id)

#수정 기능
def editMeeting(request,artist_id, meeting_id):
    user = request.user
    alerts = Alert.objects.filter(user=user)
    meeting = get_object_or_404(Meeting, id=meeting_id)
    artist = get_object_or_404(Artist, pk=artist_id)

    if request.method == 'POST':
        form = MeetingEditForm(request.POST, request.FILES, instance=meeting)
        if form.is_valid():
            form.save()
            return redirect('meeting:meeting_detail', meeting_id=meeting_id, artist_id=artist_id)
    else:
        form = MeetingEditForm(instance=meeting)

    context = {'form': form, 'meeting': meeting, 'alerts': alerts, 'artist': artist}
    return render(request, "html/meeting_edit.html", context)

#내가 작성한 모임 리스트
def writedMeetingList(request, artist_id):
    user = request.user
    alerts = Alert.objects.filter(user=user)
    artists = Artist.objects.all()
    artist = get_object_or_404(Artist, pk=artist_id)
    search = request.GET.get('search')

    meetings = Meeting.objects.filter(writeUser=user, artist=artist)
    if search:
        meetings = meetings.filter(members__User__userName__icontains=search).distinct()

    return render(request, 'html/writed_meeting_list.html', {'meetings': meetings, 'artist_id': artist_id, 'artists': artists, 'artist': artist, 'search': search, 'alerts':alerts})


#모임 신청자 수락
def memberStateAccept(request, meetingMember_id, artist_id):
    user = request.user
    alerts = Alert.objects.filter(user=user)
    member = MeetingMember.objects.get(id=meetingMember_id)
    member.memberState = MemberState.승인.value
    member.save()
    return redirect('meeting:writedMeetingList', artist_id = artist_id)

#모임 신청자 거부
def memberStateRefusal(request, meetingMember_id, artist_id):
    user = request.user
    alerts = Alert.objects.filter(user=user)
    meetingMember = get_object_or_404(MeetingMember, id=meetingMember_id)
    meetingMember.memberState = "거부"
    meetingMember.save()
    return redirect('meeting:writedMeetingList', artist_id = artist_id)

#내가 신청한 모임 목록
def applyedMeetingList(request, artist_id):
    user = request.user
    alerts = Alert.objects.filter(user=user)
    artists = Artist.objects.all()
    artist = get_object_or_404(Artist, pk=artist_id)
    meeting = Meeting.objects.filter(artist=artist)
    applyedMeetings = MeetingMember.objects.filter(User=request.user, Meeting__in=meeting)

    # URL에서 검색 쿼리 파라미터를 가져옵니다.
    search_query = request.GET.get('search')

    if search_query:
        # 검색 쿼리를 이용하여 모임을 필터링합니다.
        applyedMeetings = applyedMeetings.filter(Meeting__title__icontains=search_query)

    return render(request, 'html/applyed_meeting_list.html', {'applyedMeetings': applyedMeetings, 'artist_id': artist_id, 'artists': artists, 'artist': artist, 'alerts': alerts,})


#신청자 보호자 번호 조회
def subPNList(request, artist_id):
    user = request.user
    alerts = Alert.objects.filter(user=user)
    artists = Artist.objects.all()
    artist = get_object_or_404(Artist,pk=artist_id)
    search = request.GET.get('search')
    meetings = Meeting.objects.filter(writeUser=request.user, artist=artist)

    if search:
        meetings = meetings.filter(members__User__userName__icontains=search).distinct()

    return render(request, 'html/writed_meeting_PN.html', {'meetings': meetings, 'artist_id': artist_id,'artists' : artists,'artist' : artist, 'search': search, 'alerts':alerts,})

project/meeting/templates/html/meeting_create.html
{% extends 'base_form.html' %}
{% load static %}
{% with artist=artist alerts=alerts %}
{% block content %}

    <img class="back" src="{% static 'images/back.png'%}" alt="이전" onclick="goBack()"></img>
      <h1 class="h1-meeting">모임 작성하기</h1>
      <h3 class="h3-meeting">등록하고 싶은 모임 세부 사항을 작성해요!</h3>

      <form class="register input" id="meetingForm" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <label for="id_title" class="name" ></label>
        <input type="text" name="title" id="id_title" placeholder="모임명" required>

        <label for="id_location" class="place"></label>
        <input type="text" name="location" id="id_location" placeholder="장소" required>
      

        <input data-placeholder="일시"
        required
        aria-required="true"
        value={startDateValue}
        className={styles.selectDay}
        onChange={StartDateValueHandler} 
         class="date-placeholder" type="date" name="meetDate" id="id_meetDate" placeholder="일시" required>

        <label for="id_age" class="age"></label>
        <input type="text" name="age" id="id_age" placeholder="나이제한" required>

        <label for="id_peopleNm" class="people"></label>
        <input type="number" name="peopleNm" id="id_peopleNm" placeholder="인원" required>

        <label for="id_kakaoLink" class="openkakao"></label>
        <input type="text" name="kakaoLink" id="id_kakaoLink" placeholder="오픈 채팅방 링크" required>

        <div style="position: relative; border:none;">
        <label for="id_body"></label>
        <textarea class="detail1" name="body" id="id_body" placeholder="내용"required></textarea>
        <div class="select-wrapper " style="border:none; margin-top:-50px;">

        <label for="id_image" class="addImg-Button">사진</label>
        <input type="file" name="image" id="id_image" style="display:none" required>
        </div>
        </div>
        <input type="submit" value="항목을 모두 작성해 주세요" class="register-Button" disabled style="border-radius: 30.5px; background: #b3b1b0">
        </form>

    <script>
    let inputs = document.querySelectorAll("input");
    let startButton = document.querySelector(".register-Button");
    startButton.disabled = true;

    function checkInputs() {
    let allFilled = true;
    inputs.forEach(function(input){
    if (input.value === "") {
      allFilled = false;
      return;
    }
    });

    if (allFilled) {
    startButton.disabled = false;
    startButton.style.backgroundColor = "#BC67FF";
    startButton.value = "작성하기";
  } else {
    startButton.disabled = true;

    }
    }
    inputs.forEach(function(input){
    input.addEventListener("input", checkInputs);
    });
    function goBack() {
      window.history.back();
     }
     </script>

{% endblock %}
{% endwith %}

project/meeting/templates/html/writed_meeting_list.html
{% extends 'base_meeting.html' %}
{% load static %}
{% with artist=artist alerts=alerts %}
{% block content %}

<div style="margin-bottom: 5px; display: flex; align-items: center;" class="support_list_category">
    <button class ="allsupport" style="width:160px; margin-left:15px; font-size:20px;" onclick="location.href='{% url 'meeting:MeetingList' artist_id=artist.id %}'">모임 전체</button>
    <button class ="mysupport" style="width:160px; margin-left:24px; font-size:20px;border-bottom:3px solid #000000;" onclick="location.href='{% url 'meeting:writedMeetingList' artist_id=artist_id  %}'">나의 모임</button>
</div>

    <div class="meeting-button">
        <button class="write-button"style="  border: 1px solid #bc67ff;color:#bc67ff;" onclick="location.href='{%url 'meeting:writedMeetingList' artist_id=artist_id  %}'">작성</button>
        <button class="apply-button" onclick="location.href='{%url 'meeting:applyedMeetingList' artist_id=artist_id  %}'">신청</button>
        <button class="guardian-button"onclick="location.href='{%url 'meeting:subPNList' artist_id=artist_id  %}'">보호자</button>
        <div class="tutorial-info-icon-meeting" id="tutorial-icon">
    <img
      src="{% static 'images/information.png'%}"
      alt="info"
      class="tutorial-image-meeting-2"
      id="tutorial-image"
    />
    <div class="tutorial-hover-box-meeting" id="myModal">
      <p>
        내가 작성한 모임의 신청자들을 관리할 수 있는 페이지예요. 신청자 정보 버튼을 눌러 신청자의 활동내역을 확인해보세요!<br>
      💡사용방법이 낯설다면 모임 기능을 연습해 보는건 어떠신가요?
      </p>
      <button
        class="tutorial-box-button-meeting"
        style="width: 150px; height: 40px"
        onclick="location.href='{% url 'user:tutorial_meeting' %}'"
      >
        연습하러 가기
      </button>
    </div>
  </div>
        <div  style="margin-left:285px; margin-top:-55px;" >
            <a href="#;" onClick="zoomIn();"><img style="width:20px; height:20px;"src="{% static 'images/zoomin.png'%}" alt="확대"></a>
              <a href="#;" onClick="zoomOut();"><img style="width:20px; height:20px;"src="{% static 'images/zoomout.png'%}" alt="축소"></a>
            </div>
    </div>

    <div class="centered-container"> 
        <form class="meeting-search-form" method="get" action="{% url 'meeting:writedMeetingList' artist_id=artist_id %}">
            <label for="searchInput" style="font-size: 17px; margin-left: 10px;">검색:</label>
            <input style="width: 190px;"  type="text" id="searchInput" name="search" placeholder="신청자명을 검색하세요" style="text-indent: 0; width: 182px;">
            <button type="submit">검색</button>
        </form>
    </div>

    <div class="meeting-writed">
        {% for meeting in meetings %}
            {% if meeting.members.exists %}
                {% for meetingMember in meeting.members.all %}
                    {% if meetingMember.memberState == "대기" %}
    {% if not search or search in meetingMember.User.userName %}
        <div class="writed-lost">
            <a href="{% url 'meeting:meeting_detail' meeting_id=meeting.id artist_id=artist_id %}" style="font-size:20px; font-weight: 500;">{{ meeting.title }}</a>
            <div class="member-info">
                <h3> 신청자 : {{ meetingMember.User.userName }}</h3>
                <form method="post" action="{% url 'userWorking:show_userWorking_guest' pk=artist.id meetingMember_id=meetingMember.id %}">
                    {% csrf_token %}
                    <button class="confirm-button" type="submit">신청자 정보 확인</button>
                </form>
            </div>
            <div class="action-buttons">
                <form method="post" action="{% url 'meeting:memberStateAccept' artist_id=artist.id meetingMember_id=meetingMember.id %}">
                    {% csrf_token %}
                    <button class="accept" type="submit">수락하기</button>
                </form>
                <form method="post" action="{% url 'meeting:memberStateRefusal' artist_id=artist.id meetingMember_id=meetingMember.id %}">
                    {% csrf_token %}
                    <button class="refuse" type="submit">거부하기</button>
                </form>
            </div>
        </div>
    {% endif %}
{% endif %}

                {% endfor %}
            {% endif %}
        {% empty %}
        {% endfor %}
    </div>
<script>
    document.addEventListener("DOMContentLoaded", function () {
      const modalIcon = document.getElementById("tutorial-icon");
      const modal = document.getElementById("myModal");
      const content = document.querySelector('.content');
      const icon = document.getElementById("tutorial-image");

      modalIcon.addEventListener("click", function () {
          if (modal.style.display=="block"){
              document.body.style.overflow = 'auto';
              content.style.overflow = 'auto';
              modal.style.display = "none";
              icon.src = "{% static 'images/information.png'%}";
          }
          else {
              document.body.style.overflow = 'hidden';
              content.style.overflow = 'hidden';
              modal.style.display = "block";
              icon.src = "{% static 'images/information-hover.png'%}";
          }
      });
    });
</script>
{% endblock %}
{% endwith %}